import axios from "axios";
import { formatFormData } from "../global";

export function getUserDataReservationDetails(payload) {
  // const form = formatFormData(payload);
  // return axios.post("C_user/get_data_reservation_details", form);

  return mockRest1;
}

export function getUserModalTracking(payload) {
  return mockRest2;
}

const mockRest1 = {
  draw: "1",
  recordsTotal: 2,
  recordsFiltered: 2,
  data: [
    {
      control: "",
      totPrice: 2557476,
      dateCreated: "20-03-2023",
      requester: "Irvan Erdika",
      pta: null,
      io: "-",
      otherDoc: null,
      tracking: "C_user/get_modal_tracking/7436",
      qty_picking: "0",
      // s_wh: "<center><i class='fa fa-minus' style='color:grey;'></i></center>",
      // s_adm:
      //   "<center><i class='fa fa-hourglass-half' style='color:grey;'></i></center>",
      img: "assets/upload_img/14181679329373.png",
      x_f_ict: "Non-ICT",
      x_req_notes: "test information",
      x_ict_notes: null,
      x_purc_notes: null,
      number: "1",
      DT_RowId: "row_7436",
      idFpbDetail: "12174",
      idFpbHead: "7436",
      noFpb: "F23200194",
      noPo: null,
      materialName: "Fuel Filter",
      qty_pb: "12",
      qty_pickings: "0",
      qty_po: "12",
      uom: "UN",
      price: "213123",
      information: "test information",
      idCostCenter: "21206",
      costCenter: "SBE PPUK",
      planDate: "2023-04-28",
      picPurc: null,
      images: "14181679329373.png",
      notes: null,
      notes_po: null,
      exp_date: null,
      exp_date_po: null,
      receivedDateInv: null,
      receivedDatePo: null,
      status: "N",
      updateBy: null,
      roleName: null,
      company: "SBE",
      flag_picking: "F",
      flag_shipping: "F",
      flag_receipt: "F",
      flag_po: "T",
      flag_shipping_po: "F",
      flag_receipt_po: "F",
      flag_pjk: "N",
      flag_pjb: "N",
      flag_wh: "N",
      purc_notes: null,
      purchase_method: null,
      purc_type: null,
      flag_ict: "F",
      created_date: "2023-03-20 23:23:02",
      date_review_ict: null,
      date_appv_pjk: null,
      date_appv_pjb: null,
      date_appv_proc: null,
      date_appv_purc: null,
      flag_pjk_head: null,
      initial_pjk: null,
      initial_pjb: null,
      requesterName: "Irvan Erdika",
      idJenisKeg: "2",
      doc_pta: null,
      doc_io: null,
      doc_other: null,
      ict_notes: null,
      flag_purc_review: "F",
    },
    {
      control: "",
      totPrice: 1199999999988,
      dateCreated: "14-03-2023",
      requester: "Irvan Erdika",
      pta: "assets/upload_img/pta/14181679251289.png",
      io: null,
      otherDoc: null,
      tracking: "C_user/get_modal_tracking/7435",
      qty_picking: "0",
      // s_wh: "<center><i class='fa fa-minus' style='color:grey;'></i></center>",
      // s_adm:
      //   "<center><i class='fa fa-hourglass-half' style='color:grey;'></i></center>",
      img: null,
      x_f_ict: "Non-ICT",
      x_req_notes: "",
      x_ict_notes: null,
      x_purc_notes: null,
      number: 2,
      DT_RowId: "row_7435",
      idFpbDetail: "12173",
      idFpbHead: "7435",
      noFpb: "F23100650",
      noPo: null,
      materialName: " C Clamp Woodworking",
      qty_pb: "12",
      qty_pickings: "0",
      qty_po: "12",
      uom: "UN",
      price: "99999999999",
      information: "",
      idCostCenter: "26201",
      costCenter: "SBE BVDI",
      planDate: "2023-03-30",
      picPurc: null,
      images: null,
      notes: null,
      notes_po: null,
      exp_date: null,
      exp_date_po: null,
      receivedDateInv: null,
      receivedDatePo: null,
      status: "N",
      updateBy: null,
      roleName: null,
      company: "SBE",
      flag_picking: "F",
      flag_shipping: "F",
      flag_receipt: "F",
      flag_po: "T",
      flag_shipping_po: "F",
      flag_receipt_po: "F",
      flag_pjk: "N",
      flag_pjb: "N",
      flag_wh: "N",
      purc_notes: null,
      purchase_method: null,
      purc_type: null,
      flag_ict: "F",
      created_date: "2023-03-14 14:50:53",
      date_review_ict: null,
      date_appv_pjk: null,
      date_appv_pjb: null,
      date_appv_proc: null,
      date_appv_purc: null,
      flag_pjk_head: null,
      initial_pjk: null,
      initial_pjb: null,
      requesterName: "Irvan Erdika",
      idJenisKeg: "1",
      doc_pta: null,
      doc_io: null,
      doc_other: null,
      ict_notes: null,
      flag_purc_review: "F",
    },
  ],
};

const mockRest2 = {
  tracking_pjk: [
    {
      idUser: "1418",
      createdDate: "2023-03-20 23:23:02",
      flag_status: "N",
      noFpb: "F23200194",
      flag_pjk: null,
      flag_pjk_level: "0",
      pjk_1: "Moorly Cinny",
      pjk_2: null,
      pjk_3: null,
      date_appv_pjk1: null,
      date_appv_pjk2: null,
      date_appv_pjk3: null,
      flag_pjb: "N",
      flag_pjb_level: "0",
      flag_procurement: "N",
      flag_reviewer: "F",
      flag_checker: "N",
      date_review: null,
      date_checker: null,
      reviewer: null,
      checker: null,
    },
  ],
  tracking_pjb: [
    {
      flag_status: "N",
      flag_pjb: "N",
      flag_pjb_level: "0",
      company: "SBE",
      pjb_1: "Adrian Teja",
      pjb_2: "Fathony Rahman",
      pjb_3: "Djoko Wintoro",
      pjb_4: "Djisman Simandjuntak",
      pjb_5: "Prasasto Sudyatmiko",
      date_appv_pjb1: null,
      date_appv_pjb2: null,
      date_appv_pjb3: null,
      date_appv_pjb4: null,
      date_appv_pjb5: null,
      date_procurement: null,
    },
  ],
  max_pjkLevel: "1",
  max_pjbLevel: "5",
};
